# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160702_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.TextField(),
        ),
    ]
