# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20160702_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='idno',
            field=models.CharField(max_length=20),
        ),
    ]
